#Name : Pradyuth Vangur
#Assignment 2

#Problem 1: Rejection sampling from a truncated Gaussian

#Question 1
#Creating a sample as described in the question
sample <- rnorm(n = 10000, mean = 1, sd = 2)
head(sample)

#Generating histogram of the sample
hist(sample)

#Question 2
#Creating trunc_norm in order to generate number between (lower, upper)
k <- 1

#Creating function with the required inputs
trunc_norm <- function(mean, sd, lower = -Inf, upper = Inf, num_samp = 1){
#Creating dataframe to store the data in the rows and columns represent the sample number
  trunc_sample <- data.frame()
#Generating sample sets of truncated gaussian data
  for(k in 1:num_samp){
    i <- 1
    j <- 1
#Generating random normalised data
    sample <- rnorm(n = 10000, mean = mean, sd = sd)
    while(i <= length(sample)){
#Converting each number from the normal Gaussian distribution to truncated distribution
      trunc_sample[j, k] <- (sample[i] - range(sample)[1]) * ((upper - lower) / (diff(range(sample)))) + lower
      i = i + 1
      j = j + 1
      }
  }
  return(trunc_sample)
}

#Question 3
#Generating the truncated numbers between 0 and 5
num <- trunc_norm(mean = 1, sd = 2, lower = 0, upper = 5)
head(num)
#We obtain the data in a list form which has to be unlisted to be histogrammed
hist(unlist(num), xlab = "Truncated numbers", main = expression("Truncated numbers histogram"))

#Question 4
#Creating function with the required inputs
trunc_norm_vec <- function(mean, sd, lower = -Inf, upper = Inf, num_samp = 1){
  sample_vec <- rnorm(10000, mean = mean, sd = sd)
  z <- 1
#Matrix represents the data samples with columns refering to the sample numbers
  trunc_sample_vec <- matrix(nrow = 10000, ncol = num_samp)
  while(z <= num_samp){
    trunc_sample_vec[,z] <- (sample_vec - range(sample_vec)[1]) * ((upper - lower) / diff(range(sample_vec))) + lower
    z = z + 1
  }
  return(trunc_sample_vec)
}

#Question 5
#Generating truncated numbers between 0 and 5
num_vec <- trunc_norm_vec(mean = 1, sd = 2, lower = 0, upper = 5)
head(num_vec)

#Generating histogram
hist(unlist(num_vec), xlab = "Truncated vector numbers", main = expression("Truncated numbers vector histogram"))

#Question 6
#System time for normal function with loops
system.time(trunc_norm(mean = 1, sd = 2, lower = 0, upper = 5, num_samp = 4))

#System time for normal function with vectors
system.time(trunc_norm_vec(mean = 1, sd = 2, lower = 0, upper = 5, num_samp = 4))

#Problem 2: Calculating Entropy

#Question 1
#Generating variables of mean 1 and sd 1
ent_vec <- matrix(rnorm(60000, mean = 1, sd = 1), ncol = 6)
head(ent_vec)

#Setting all negative elements to zero
ent_vec[which(ent_vec < 0)] <- 0

#Rescaling rows of matrix to one
ent_vec_sum <- rowSums(ent_vec)
head(ent_vec_sum)

#Reducing the sum of vectors in each row to one
ent_vec <- ent_vec / ent_vec_sum
head(ent_vec)

#Question 2
#Calculation of entropy of each element
#Method 1: Calculating by using na.rm inside the function
ent <- -ent_vec * log(ent_vec)
#Calculation of entropy of each row
ent_row_1 <- rowSums(ent, na.rm = TRUE)
head(ent_row_1)

#Method 2: Calculating by assigning 0 to NaN values
ent2 <- -ent_vec * log(ent_vec)
ent2[which(ent2 == "NaN")] <- 0
ent_row_2 <- rowSums(ent2)
head(ent_row_2)

#We observe the output generated by both methods are same.

#Question 3
#Method 1
hist(ent_row_1, xlab = "Entropy", main = expression("Entropy Histogram method 1"))

#Method 2
hist(ent_row_2, xlab = "Entropy", main = expression("Entropy Histogram method 2"))

#Question 4
#Largest entropy observed
ent_row_1[which(ent_row_1 == max(ent_row_1))]

#Corresponding vector
which(ent_row_1 == max(ent_row_1))

#Question 5
#Entropy refers to the measure of information in the probability information.
#Higher entropy refers to the less information and lower entropy refers to large
#amount of information.